apiVersion: v1
kind: Secret
metadata:
  name: orbitiq-secrets
  namespace: orbitiq
type: Opaque
stringData:
  database-url: "postgresql://orbitiq_admin:CHANGE_ME@orbitiq-db.orbitiq.svc.cluster.local:5432/orbitiq"
  redis-url: "redis://orbitiq-redis.orbitiq.svc.cluster.local:6379"
  auth-secret: "CHANGE_ME_TO_RANDOM_64_CHARS"
  keycloak-secret: "CHANGE_ME"
